import "./globals.css";
import { Navbar } from "../components/navbar";
import Footer from "../components/footer";

export const metadata = {
  title: "E-commerce App",
  description: "Generated by Ibrahim",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-neutral-300">
        <Navbar />
        <main className="flex-grow container  mx-auto px-4 py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
